In [23]:
import pandas as pd
import numpy as np
dataframe = pd.read_csv('E:/COLLEGE PDFS/5TH SEMESTER/Machine Learning/purchaseData.csv')
print(dataframe)
print("\n")
A = dataframe[['Candies (#)', 'Mangoes (Kg)', 'Milk Packets (#)']].values
C = dataframe['Payment (Rs)'].values

print("Matrix A : \n", A)
print("\nMatrix C : \n", C)

  Customer  Candies (#)  Mangoes (Kg)  Milk Packets (#)  Payment (Rs)
0      C_1           20             6                 2           386
1      C_2           16             3                 6           289
2      C_3           27             6                 2           393
3      C_4           19             1                 2           110
4      C_5           24             4                 2           280
5      C_6           22             1                 5           167
6      C_7           15             4                 2           271
7      C_8           18             4                 2           274
8      C_9           21             1                 4           148
9     C_10           16             2                 4           198


Matrix A : 
 [[20  6  2]
 [16  3  6]
 [27  6  2]
 [19  1  2]
 [24  4  2]
 [22  1  5]
 [15  4  2]
 [18  4  2]
 [21  1  4]
 [16  2  4]]

Matrix C : 
 [386 289 393 110 280 167 271 274 148 198]


In [28]:
dimension = A.shape[1]
print("Dimentionality of the vector space :", dimension)

num = A.shape[0]
print("Number of vectors in vector space: ", num)

rank = np.linalg.matrix_rank(A)
print("Rank: ", rank, "\n")

A_pseudo_inv = np.linalg.pinv(A)
X = A_pseudo_inv @ C

print("Cost per product:")
print(f"Price per Candy: ₹{X[0]:.2f}")
print(f"Price per Kg of Mangoes: ₹{X[1]:.2f}")
print(f"Price per Milk Packet: ₹{X[2]:.2f}")

Dimentionality of the vector space : 3
Number of vectors in vector space:  10
Rank:  3 

Cost per product:
Price per Candy: ₹1.00
Price per Kg of Mangoes: ₹55.00
Price per Milk Packet: ₹18.00
