#A1

In [40]:
import pandas as pd             #importing pandas package
import numpy as np              #importing numpy package

dataframe = pd.read_csv('E:/COLLEGE PDFS/5TH SEMESTER/Machine Learning/purchaseData.csv')   #read the csv file which contains the input for purchase data
print(dataframe)
print("\n")
A = dataframe[['Candies (#)', 'Mangoes (Kg)', 'Milk Packets (#)']].values           #creating a matrix for inputs
C = dataframe['Payment (Rs)'].values                                                #creating a matrix for the output

print("Matrix A : \n", A)
print("\nMatrix C : \n", C)

  Customer  Candies (#)  Mangoes (Kg)  Milk Packets (#)  Payment (Rs)
0      C_1           20             6                 2           386
1      C_2           16             3                 6           289
2      C_3           27             6                 2           393
3      C_4           19             1                 2           110
4      C_5           24             4                 2           280
5      C_6           22             1                 5           167
6      C_7           15             4                 2           271
7      C_8           18             4                 2           274
8      C_9           21             1                 4           148
9     C_10           16             2                 4           198


Matrix A : 
 [[20  6  2]
 [16  3  6]
 [27  6  2]
 [19  1  2]
 [24  4  2]
 [22  1  5]
 [15  4  2]
 [18  4  2]
 [21  1  4]
 [16  2  4]]

Matrix C : 
 [386 289 393 110 280 167 271 274 148 198]


In [41]:
dimension = A.shape[1]                  
print("Dimentionality of the vector space :", dimension)

num = A.shape[0]
print("Number of vectors in vector space: ", num)

rank = np.linalg.matrix_rank(A)
print("Rank: ", rank, "\n")

A_pseudo_inv = np.linalg.pinv(A)                        #pseudo inverse of A
X = A_pseudo_inv @ C

print("Cost per product:")
print(f"Price per Candy: ₹{X[0]:.2f}")
print(f"Price per Kg of Mangoes: ₹{X[1]:.2f}")
print(f"Price per Milk Packet: ₹{X[2]:.2f}")

Dimentionality of the vector space : 3
Number of vectors in vector space:  10
Rank:  3 

Cost per product:
Price per Candy: ₹1.00
Price per Kg of Mangoes: ₹55.00
Price per Milk Packet: ₹18.00


---------------------------------------------------------------------------------------------------------------------------------------------------------
#A2

In [42]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix


dataframe['Class'] = dataframe['Payment (Rs)'].apply(lambda x: 'RICH' if x > 200 else 'POOR')

# Define features and labels
X = dataframe[['Candies (#)', 'Mangoes (Kg)', 'Milk Packets (#)']]
y = dataframe['Class']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)           #train test split

# Train classifier
clf = LogisticRegression()
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)                # Prediction of costs

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

#save it in dataframe and display the prediction
dataframe['Predicted Class'] = clf.predict(X)
display(dataframe)


Confusion Matrix:
[[2 0]
 [1 0]]

Classification Report:
              precision    recall  f1-score   support

        POOR       0.67      1.00      0.80         2
        RICH       0.00      0.00      0.00         1

    accuracy                           0.67         3
   macro avg       0.33      0.50      0.40         3
weighted avg       0.44      0.67      0.53         3



e:\COLLEGE PDFS\5TH SEMESTER\Machine Learning\ML\machine-learning-lab\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
e:\COLLEGE PDFS\5TH SEMESTER\Machine Learning\ML\machine-learning-lab\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
e:\COLLEGE PDFS\5TH SEMESTER\Machine Learning\ML\machine-learning-lab\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zer

Customer  Candies (#)  Mangoes (Kg)  Milk Packets (#)  Payment (Rs) Class  \
0      C_1           20             6                 2           386  RICH   
1      C_2           16             3                 6           289  RICH   
2      C_3           27             6                 2           393  RICH   
3      C_4           19             1                 2           110  POOR   
4      C_5           24             4                 2           280  RICH   
5      C_6           22             1                 5           167  POOR   
6      C_7           15             4                 2           271  RICH   
7      C_8           18             4                 2           274  RICH   
8      C_9           21             1                 4           148  POOR   
9     C_10           16             2                 4           198  POOR   

  Predicted Class  
0            RICH  
1            POOR  
2            RICH  
3            POOR  
4            RICH  
5            POOR  
6            RICH  
7            RICH  
8            POOR  
9            POOR